name: "Commit Verification"
description: "Verifies commit signatures for both repository commits and third-party dependencies"
branding:
  icon: "shield"
  color: "blue"

inputs:
  repository:
    description: "The full GitHub repository (e.g. owner/repo)"
    required: true
  branch:
    description: "The branch name"
    required: true
  token:
    description: "GitHub token"
    required: true
  commits-to-check:
    description: "Number of commits to check (or 'all')"
    required: false
    default: "all"
  time-range:
    description: "Time-range duration for time-based checking (e.g. '6 months', '4320h'). Leave empty for no limit"
    required: false
    default: "6 months"
  key-age-period:
    description: "Check PGP key age (e.g. '730h', '1 week'). Leave empty for no requirement"
    required: false
    default: ""
  repo-policy:
    description: "Repository policy (colon-separated: expired:untrusted:uncertified:missingkey:github-automated:unsigned:unauthorized)"
    required: false
    default: "false:false:false:false:true:false:false"
  deps-policy:
    description: "Dependencies policy (colon-separated: expired:untrusted:uncertified:missingkey:github-automated:unsigned:unauthorized)"
    required: false
    default: "true:true:true:true:true:true:true"
  output-format:
    description: "Output format ('json' or 'console')"
    required: false
    default: "json"
  output-file:
    description: "Output file name for JSON reports"
    required: false
    default: "signature-report.json"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.branch }}
    - ${{ inputs.token }}
    - ${{ inputs.commits-to-check }}
    - ${{ inputs.time-range }}
    - ${{ inputs.key-age-period }}
    - ${{ inputs.repo-policy }}
    - ${{ inputs.deps-policy }}
    - ${{ inputs.output-format }}
    - ${{ inputs.output-file }}